<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Customer\Block\Account\Customer $block */

?>

<li class="customer-welcome">
    <span class="customer-name"
            role="link"
            tabindex="0"
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            data-trigger-keypress-button="true"
            data-bind="scope: 'customer'">
        <?php if ($block->customerLoggedIn()) { ?> 
            <span data-bind="text: new String('<?= $block->escapeHtml(__('%1!', '%1')) ?>').replace('%1', customer().fullname)"></span>
        <?php } else { ?> 
            <span><?php echo __('My Account');?></span>
        <?php } ?> 
        <button type="button"
                class="action switch"
                tabindex="-1"
                data-action="customer-menu-toggle">
            <span><?php /* @escapeNotVerified */ echo __('Change')?></span>
        </button>
    </span>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
    
    <div class="customer-menu" data-target="dropdown">
        <ul class="header links">
            <?php
                if($block->customerLoggedIn()): 
                    //echo $block->getLayout()->getBlock('orders-link')->toHtml();
                    echo $block->getLayout()->getBlock('my-account-link')->toHtml();
                    echo $block->getLayout()->getBlock('wish-list-link')->toHtml();
                    echo $block->getLayout()->getBlock('catalog.compare.link')->toHtml();
                    echo $block->getLayout()->getBlock('authorization-link')->toHtml();
                else: 
                    echo $block->getLayout()->getBlock('authorization-link')->toHtml();
                    echo $block->getLayout()->getBlock('register-link')->toHtml();
                    echo $block->getLayout()->getBlock('catalog.compare.link')->toHtml();
                endif; 
            ?>
        </ul>
    </div>
</li>
