<?php

/** @var \Magento\Framework\View\Element\Template $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$getBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->get('Magento\Customer\Model\Session');



?>

<div class="has-toggle quick-access"  id="quick-access">
    <div class="btn-toggle">
    <strong><?php echo __('My Account'); ?></strong>
    </div>
    <div class="inner-toggle">
        <div class="shop-access">
                <ul class="links">
                <li class="first"><a href="<?=$getBaseUrl;?>catalog/product_compare/index/" title="Compare Products">Compare Products</a></li>
                <li><a href="<?=$getBaseUrl;?>customer/account/" title="My Account">My Account</a></li>
                <li><a href="<?=$getBaseUrl;?>wishlist/" title="My Wishlist">My Wishlist</a></li>
                <?php if($customerSession->isLoggedIn()): ?>
                    <li class=" last"><a href="<?=$getBaseUrl;?>customer/account/logout/"><?php /* @escapeNotVerified */ echo __('Sign Out') ?></a></li>
                <?php else: ?>	
                    <li><a href="<?=$getBaseUrl;?>customer/account/create/" title="Create An Account">Create An Account</a></li>
                    <li class=" last"><a href="<?=$getBaseUrl;?>customer/account/login/" title="Log In">Log In</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>