<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

 /** @var \CasaLum\BannerSlider\Block\Widget\BannerSlider $block */
$banners = $block->getBannersCollection();
$sliderId = $block->getIdSlider() . uniqid('-', false);
$SldierOptions = $block->getBannerOptions();
?>
<?php if (!empty($banners) && $banners->getSize()): ?>
    <div id="bannerslider-<?=/* @noEscape */ $sliderId ?>" class="owl-carousel owl-theme">
        <?php foreach ($banners as $banner): ?>
            <div class="item">
                <?php if ($banner->getUrl()): ?>
                    <a href="<?= $banner->getUrl(); ?>" title="<?= $banner->getName(); ?>">
                <?php endif; ?>
                <img src="<?= $banner->getImageUrl(); ?>" alt="<?= $banner->getName(); ?>" width="100%"/>
                <?php if ($banner->getUrl()): ?>
                    </a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <script type="text/javascript">
        require([
            'jquery', 
            'owlcarousel'
        ], function($) {
            $('#bannerslider-<?= /* @noEscape */ $sliderId ?>').owlCarousel(<?= /* @noEscape */ $SldierOptions ?>);
        });
    </script>
<?php endif; ?>