<?php 
    $productCollection = $block->getLoadedProductCollection(); 
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="block block-product-slider slider-list">
    <div class="block-title">
        <h2><?php echo $block->getTitle() ?></h2>
    </div>
    <div class="block-content">
        <?php if(count($productCollection)): ?>
            <div class="product-slider">
                <?php foreach($productCollection as $product): ?>
                    <div class="product">
                        <div class="product-image">
                            <a href="<?php echo $product->getProductUrl() ?>">
                                <?php 
                                    echo $block->getImage($product,'category_page_grid')->toHtml() 
                                ?>
                            </a>
                        </div>
                        <strong class="product-name">
                            <a
                                href="<?php echo $product->getProductUrl() ?>">
                                <?php echo $_helper->productAttribute($product,$product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getProductPrice($product) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
require(['jquery', 'slick'], function($){
    $(function(){
        $('.product-slider').slick({
            dots: true,
            centerMode: true,
            centerPadding: '60px',
            slidesToShow: 3,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
            responsive: [
                {
                breakpoint: 768,
                settings: {
                    arrows: false,
                    centerMode: true,
                    centerPadding: '40px',
                    slidesToShow: 3
                }
                },
                {
                breakpoint: 480,
                settings: {
                    arrows: false,
                    centerMode: true,
                    centerPadding: '40px',
                    slidesToShow: 1
                }
                }
            ]
        });
    });
});
</script>